set(SFML_FOUND 1)
set(SFML_ROOT "${CMAKE_SOURCE_DIR}/dep/SFML-2.1")
set(SFML_DIR "${CMAKE_SOURCE_DIR}/dep/SFML-2.1")
set(SFML_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/dep/SFML-2.1/include")
set(SFML_LIBRARIES "sfml-graphics" "sfml-window" "sfml-system")
set(SFML_DEPENDENCIES "")